SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[A_SP_APP_COPY_FILE]
 @files_copy VARCHAR(2000)=''
,@forecast_to int   
,@commands varchar(2000)=''
,@session_id nvarchar(50)  = null -- session id for loging, keep empty for an autogenerated uid
,@site_id int = 0 -- site to run
,@suffix nvarchar(255) =''
AS
BEGIN

    SET NOCOUNT ON;
    SET DATEFIRST 1

    DECLARE @output nvarchar(max)='';
    DECLARE @rows INT   -- keep affected rows
    DECLARE @data  varchar(4000)=''  -- log data
    DECLARE @procedure_name nvarchar(200)='A_SP_APP_COPY_FILE'
    DECLARE @rows_existing INT   -- check existing rows

    BEGIN TRY

        --SET @site_id = (SELECT top 1 site_id from [dbo].[A_IMPORT]
        --where import_id in (SELECT * FROM STRING_SPLIT(@imports_copy,',')))

        SET @rows_existing = (SELECT count(*) from [dbo].[A_IMPORT_FILE]
        where active=1 and file_id in (SELECT * FROM STRING_SPLIT(@files_copy,',')))

        INSERT INTO [dbo].[A_IMPORT_FILE]
(
		 [file_name]
		,[source]
		,[domain]
		,[attributes]
		,[category]
		,[description]
		,[status]
		,[file_created]
		,[file_updated]
		,[file_last_access]
		,[size]
		,[field_date]
		,[field_date_format]
		,[forecast_id]
		,[activity_set]
		,[activity_id]
		,[rows_skip]
		,[fields]
		,[session]
		,[site_id]
		,[active]
		,[file_guid]
		,[tab]
		,[records]
		,[field_interval]
		,[field_interval_format]
		,[date_min]
		,[date_max]
		,[filter_delete]
		,[filter_update]
		,[swap_dot_comma]
		,[date_created]
		,[date_updated]
		,[commands]
		,[file_reader]
		,[days_back]
		,[days_forward]
		,[date_run]
		,[file_data]
		,[file_date_min]
		,[file_date_max]
		,[file_records]
		,[region]
		,[slicer1]
		,[slicer2]
		,[slicer3]
		,[metadata]
		,[service_id]
		,[type]
)
SELECT 
[file_name]  
		,[source]
		,[domain]
		,[attributes]
		,case when @suffix>'' then [category] + @suffix else category end
		,[description]
		,[status]
		,[file_created]
		,[file_updated]
		,[file_last_access]
		,[size]
		,[field_date]
		,[field_date_format]
		,case when @forecast_to is not null then @forecast_to else [forecast_id] end
		,[activity_set]
		,[activity_id]
		,[rows_skip]
		,[fields]
		,@session_id
		,@site_id
		,[active]
		,newid()
		,[tab]
		,[records]
		,[field_interval]
		,[field_interval_format]
		,[date_min]
		,[date_max]
		,[filter_delete]
		,[filter_update]
		,[swap_dot_comma]
		,[date_created]
		, getdate()  
		,[commands]
		,[file_reader]
		,[days_back]
		,[days_forward]
		,[date_run]
		,[file_data]
		,[file_date_min]
		,[file_date_max]
		,[file_records]
		,[region]
		,[slicer1]
		,[slicer2]
		,[slicer3]
		,[metadata]
		,[service_id]
		,[type]
         
        FROM [dbo].[A_IMPORT_FILE]
        where file_id in (SELECT * FROM STRING_SPLIT(@files_copy,','))
        and site_id=@site_id;

        SET @rows= @@ROWCOUNT;
        SET @output=@output+'Number of files copied : ' + convert(varchar(10),@rows)+'<br>'  
        IF @suffix>'' BEGIN SET @output= @output+ 'Category modified witg suffix ' + @suffix +'<br>'  END 

    

    END TRY
 		BEGIN CATCH  
            SET @data=JSON_MODIFY( @data,'$.error',dbo.[A_FN_SYS_ErrorJson]()) 
            PRINT @data;
            SET @output=@output+'<br>ERROR on copying files.<br>'+@data+'<br><br>';
            EXEC dbo.[A_SP_SYS_LOG] 'ERROR APP - FILE COPY' ,null , @procedure_name, @files_copy ,@forecast_to,@site_id;  
 		END CATCH;   


    IF @commands like '%-OUTPUT%'  select @output as SQL_OUTPUT


END
GO



-- TEST
-- EXEC dbo.A_SP_APP_COPY_FILE @files_copy='828,827,826,819,820,822,821,824,825,823,818,817,816', @site_id=1,@forecast_to=4,@suffix='2025', @commands='-OUTPUT ',@session_id='' 
