SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[A_SP_APP_COPY_IMPORT]
 @imports_copy VARCHAR(2000)=''
,@forecast_to int = 0 -- run imports for a forecast_id
,@commands varchar(2000)=''
,@session_id nvarchar(50)  = null -- session id for loging, keep empty for an autogenerated uid
,@site_id int = 0 -- site to run
AS
BEGIN

    SET NOCOUNT ON;
    SET DATEFIRST 1

    DECLARE @output nvarchar(max)='';
    DECLARE @rows INT   -- keep affected rows
    DECLARE @data  varchar(4000)=''  -- log data
    DECLARE @procedure_name nvarchar(200)='A_SP_APP_COPY_IMPORT'
    DECLARE @rows_existing INT   -- check existing rows

    BEGIN TRY

        --SET @site_id = (SELECT top 1 site_id from [dbo].[A_IMPORT]
        --where import_id in (SELECT * FROM STRING_SPLIT(@imports_copy,',')))

        SET @rows_existing = (SELECT count(*) from [dbo].[A_IMPORT]
        where active=1 and import_id in (SELECT * FROM STRING_SPLIT(@imports_copy,',')))

        INSERT INTO [dbo].[A_IMPORT] (
            [import_code]
            ,[domain]
            ,[procedure_id]
            ,[procedure_code]
            ,[activity_id]
            ,forecast_id
            ,[source]
            ,[filter]
            ,[fields_source]
            ,[fields_target]
            ,[group_by]
            ,[category]
            ,[status]
            ,[version]
            ,[commands]
            ,[p1]
            ,[p2]
            ,[p3]
            ,[p4]
            ,[p5]
            ,[schedule]
            ,[days_back]
            ,[days_forward]
            ,[date_import_from]
            ,[date_import_until]
            ,[description]
            ,[sort_order]
            ,[active]
            ,[template_id]
            ,[site_id]
            ,[date_updated]
            ,[date_created]
            ,[import_guid]
        )
        SELECT  [import_code]
            ,[domain]
            ,[procedure_id]
            ,[procedure_code]
            ,[activity_id]
            ,@FORECAST_TO as forecast_id
            ,[source]
            ,[filter]
            ,[fields_source]
            ,[fields_target]
            ,[group_by]
            ,[category]
            ,[status]
            ,[version]
            ,[commands]
            ,[p1]
            ,[p2]
            ,[p3]
            ,[p4]
            ,[p5]
            ,[schedule]
            ,[days_back]
            ,[days_forward]
            ,[date_import_from]
            ,[date_import_until]
            ,[description]
            ,[sort_order]
            ,[active]
            ,[template_id]
            ,[site_id]
            ,getdate() [date_updated]
            ,getdate() [date_created]
            ,newid() as [import_guid]
        FROM [dbo].[A_IMPORT]
        where import_id in (SELECT * FROM STRING_SPLIT(@imports_copy,','));

        SET @rows= @@ROWCOUNT;
        SET @output=@output+'Number of imports copied : ' + convert(varchar(10),@rows)+'<br>'  

    --SET @commands= @commands + ' -DATADAY';
    -- copy day data
    IF @commands like '%DATADAY%'
    BEGIN
        ;WITH I as (
            SELECT N.import_id ni, O.import_id oi 
            from [dbo].A_IMPORT N 
            inner join [dbo].A_IMPORT O on 
                N.activity_id = O.activity_id
                and O.import_id in (SELECT * FROM STRING_SPLIT(@imports_copy,','))
            where N.forecast_id=@forecast_to 
        )
        INSERT INTO [dbo].A_FACT_DAY 
        ( [date]
            ,[activity_id]
            ,[forecast_id] -- replace forecast
            ,[value1]
            ,[value2]
            ,[value3]
            ,[value4]
            ,[value5]
            ,[value6]
            ,[value7]
            ,[value8]
            ,[value9]
            ,[value10]
            ,[site_id]
            ,import_id -- replace old import id with the new one
            ,[date_updated])
        SELECT   [date]
            ,[activity_id]
            ,@forecast_to [forecast_id] -- replace forecast
            ,[value1]
            ,[value2]
            ,[value3]
            ,[value4]
            ,[value5]
            ,[value6]
            ,[value7]
            ,[value8]
            ,[value9]
            ,[value10]
            ,[site_id]
            ,I.[ni] import_id -- replace old import id with the new one
            ,[date_updated]
        FROM [dbo].[A_FACT_DAY] F
        inner join I on F.import_id=I.oi

        SET @rows= @@ROWCOUNT;
        SET @output=@output+'Number of days data copied : ' + convert(varchar(10),@rows)+'<br>'  

    END

    END TRY
 		BEGIN CATCH  
            SET @data=JSON_MODIFY( @data,'$.error',dbo.[A_FN_SYS_ErrorJson]()) 
            PRINT @data;
            SET @output=@output+'<br>ERROR on copying imports.<br>'+@data+'<br><br>';
            EXEC dbo.[A_SP_SYS_LOG] 'ERROR APP - IMPORT COPY' ,null , @procedure_name, @imports_copy ,@forecast_to,@site_id;  
 		END CATCH;   


    IF @commands like '%-OUTPUT%'  select @output as SQL_OUTPUT


END
GO
